# Author: Sakthi Santhosh
# Created on: 17/01/2023
#
# Generated by Django 5.0.1 on 2024-01-16 09:58
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(code="invalid_first_name", message="First name can contain only alphabets.", regex="^[A-Za-z]+$")])),
                ("last_name", models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(code="invalid_last_name", message="Last name can contain only alphabets.", regex="^[A-Za-z]+$")])),
                ("email", models.EmailField(max_length=254, unique=True))
            ]
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(code="invalid_tag", message="Tags can only contain alphanumeric characters and underscores.", regex="^[\\w]+$")]))
            ]
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=256)),
                ("notes", models.TextField(null=True)),
                ("related_url", models.URLField(null=True)),
                ("reminder", models.DateTimeField(null=True)),
                ("location", models.CharField(max_length=64, null=True)),
                ("flag", models.BooleanField(default=False)),
                ("priority", models.CharField(choices=[("P0", "High"), ("P1", "Medium"), ("P2", "Low")], max_length=2, null=True)),
                ("invitees", models.ManyToManyField(related_name="invited_tasks", related_query_name="invited_task", to="api.invitee")),
                ("tags", models.ManyToManyField(related_name="tasks", related_query_name="task", to="api.tag"))
            ]
        ),
        migrations.CreateModel(
            name="SubTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=256)),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sub_tasks", related_query_name="sub_task", to="api.task"))
            ],
            options={
                "db_table": "api_sub_task"
            }
        ),
        migrations.CreateModel(
            name="TaskGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=256)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="task_groups", related_query_name="task_group", to=settings.AUTH_USER_MODEL))
            ],
            options={
                "db_table": "api_task_group"
            }
        ),
        migrations.AddField(
            model_name="task",
            name="task_group",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tasks", related_query_name="task", to="api.taskgroup")
        )
    ]
